### ISSUE TITLE
generate colours based on a base colour

### ISSUE THREAD

**Issue by zwq000** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.480#1]
Less understanding of the way you need color generation, such as adjacent color, complementary color, usually need to introduce other color controls, RGB color controls can not be used for color calculation. It can only be used to represent color.

You can use HSB (hue/saturation/brightness) to calculate.

For example, keeping saturation unchanged, modifying hue to produce a new color.

**Comment by Wagnerp** [comment]
Hi @zwq000 

Thanks for your comment, what I'm looking for is something like this: http://paletton.com/#uid=14Y0u0kecqd5bGZ9tv9j8lDnBha. I'll look into HSB, thanks!
